import { Providers } from "@/store/provider";
import "../../public/assets/scss/app.scss";
import "leaflet/dist/leaflet.css";
import "leaflet-control-geocoder/dist/Control.Geocoder.css";
import "react-phone-input-2/lib/style.css";

import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import ErrorBoundary from "@/Common/ErrorBoundry";

export const metadata: Metadata = {
  title: "Tripssource-Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="ltr">
      <head>
        <link rel="icon" href="/mark.png" type="image/png" sizes="any" />
      </head>
      <body>
        <ErrorBoundary>
          <Providers>{children}</Providers>
          <ToastContainer />
        </ErrorBoundary>
      </body>
    </html>
  );
}
